apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-ntwmkpfs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-ntwmkpfs 
  name: go-ntwmkpfs
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-ntwmkpfs
    weight: 100 
